version: "3"
services:
  v2raya:
    container_name: v2raya
    image: mzz2017/v2raya
    restart: always
    network_mode: "host"
    privileged: true
    environment:
      - V2RAYA_ADDRESS=0.0.0.0:2017
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
      - ./v2raya:/etc/v2raya
